export const GENERATE_CARD = "GENERATE_CARD";
export const CLEAR_SEARCH_STATE = "CLEAR_SEARCH_STATE";
export const SEARCH_CARDS_SUCCESS = "SEARCH_CARDS_SUCCESS";
export const SEARCH_CARDS_FAILED = "SEARCH_CARDS_FAILED";
export const SEARCH_CARDS_LOADING = "SEARCH_CARDS_LOADING";
export const SEARCH_RANDOM_CARD_IMAGE = "SEARCH_RANDOM_CARD_IMAGE";
